{% set name = "mistralai" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mistralai-{{ version }}.tar.gz
  sha256: 5eb656710517168ae053f9847b0bb7f617eda07f1f93f946ad6c91a4d407fd93

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9,<4.0
    - orjson >=3.9.10,<3.11
    - pydantic >=2.5.2,<3
    - httpx >=0.25,<1

test:
  imports:
    - mistralai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mistralai/client-python
  summary: Python client library for Mistral AI platform 
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - jtpio
