{% set name = "mistralai" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mistralai-{{ version }}.tar.gz
  sha256: 46fb4407d1a4161b23e1b2c4c735478433fb7a41abb05facd23272fb05d171b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9,<4.0
    - orjson >=3.9.10,<3.11
    - pydantic >=2.5.2,<3
    - httpx >=0.25,<1

test:
  imports:
    - mistralai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mistralai/client-python
  summary: Python client library for Mistral AI platform
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
