context:
  version: "1.10.0"

package:
  name: mistralai
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/mistralai/mistralai-${{ version }}.tar.gz
  sha256: c92e9a5ec7057577b326d47a4b1c186f42660bccbe95167fc25c686fe658ad23

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python ${{ python_min }}.*
    - eval-type-backport >=0.2.0
    - httpx >=0.28.1
    - pydantic >=2.10.3
    - python-dateutil >=2.8.2
    - typing-inspection >=0.4.0
    - pyyaml >=6.0.2,<7.0.0
    - invoke >=2.2.0,<3.0.0
    - opentelemetry-sdk >=1.33.1,<2.0.0
    - opentelemetry-api >=1.33.1,<2.0.0
    - opentelemetry-exporter-otlp-proto-http >=1.37.0,<2.0.0
    - opentelemetry-semantic-conventions >=0.59b0,<0.60a0

tests:
  - python:
      imports:
        - mistralai
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/mistralai/client-python
  summary: Python client library for Mistral AI platform
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - jtpio
