context:
  version: "1.9.11"

package:
  name: mistralai
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/mistralai/mistralai-${{ version }}.tar.gz
  sha256: 3df9e403c31a756ec79e78df25ee73cea3eb15f86693773e16b16adaf59c9b8a

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python ${{ python_min }}.*
    - eval-type-backport >=0.2.0
    - httpx >=0.28.1
    - pydantic >=2.10.3
    - python-dateutil >=2.8.2
    - typing-inspection >=0.4.0
    - pyyaml >=6.0.2,<7.0.0
    - invoke

tests:
  - python:
      imports:
        - mistralai
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/mistralai/client-python
  summary: Python client library for Mistral AI platform
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - jtpio
